### ISSUE TITLE
"Cannot GET /" error when opening page

### ISSUE THREAD

**Issue by Remarci225** [petya0927/watch2gether#1]
Basically, the only thing the page is displaying is the "Cannot GET /" text. I got a "Failed to load resource: the server responded with a status of 404 ()" in the dev console.

Platform: 
- Browser: Google Chrome - version 105.0.5195.127, 64 bit
- OS: Windows 10 - version 21H1, 19043.1889, 64 bit

**Comment by petya0927** [comment]
Thx, my bad, I accidentally put the link to the backend, I fixed it
